Fix package imports related to PR #9
In order for ``csvgrader`` to be run as
described in the README, the imports in
``mainWindow.py`` must be relative imports.

If we also want to keep supporting ``mainGUI.py``
then it needs to be moved up a level in the
directory tree and changed to an absolute
import of the ``csvgrader`` package, so that
``csvgrader/__init__.py`` will be read first
and there will be no errors like:
```
ImportError: attempted relative import with no known parent package
```

But ``mainGUI.py`` is also somewhat redundant
with the intended functionality of ``csvgrader/__main__.py``
which is accessed if the package is run as
```
python -m csvgrader
```